#!/bin/bash

cat <&0 >  ./side-cars/kustomize/base/manifests.yaml

if [ "$(command -v kustomize)" ]; then
    kustomize build ./side-cars/kustomize/openshift/

else
    oc kustomize ./side-cars/kustomize/openshift/
fi

