apiVersion: v1
kind: Service
metadata:
  name: {{ include "firstapp.fullname" . }}
  labels:
    {{- include "firstapp.labels" . | nindent 4 }}
  annotations:
    anno: atLeastOne
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "firstapp.selectorLabels" . | nindent 4 }}
