apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  annotations:
    tests/injectWiremockSideCar: "true"
    tests/injectKafkaSideCar: "true"
    tests/injectPostgresqlSideCar: "true"
    postgresqlSideCarDB: "orders"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      labels:
        app: app
      annotations:
        tests/injectWiremockSideCar: "true"
        tests/injectKafkaSideCar: "true"
        tests/injectPostgresqlSideCar: "true"
        postgresqlSideCarDB: orders

    spec:
      containers:
      - image: ubi8/ubi:8.5-226
        name: ubi
        command: ["bash", "-c" , "sleep infinity" ]
