resources:
  - manifests.yaml
#  - deployment.yaml
  - database-postgresql/

    
patches:
  - path: pull-secret.yaml
    target:
      kind: Deployment
      name: ".*"
  - path: sidecar-wiremock.yaml
    target:
      kind: Deployment
      annotationSelector: "tests/injectWiremockSideCar=true"
      name: ".*"

  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: doesNotMatter
      spec:
        ports:
          - name: wiremock
            protocol: TCP
            port: 9999
            targetPort: 9999
    target:
      kind: Service
      name: ".*"

#  - path: sidecar-mongodb.yaml
#    target:
#      kind: Deployment
#      annotationSelector: "tests/injectMongoDBSideCar=true"
#      name: ".*"
#
  - path: sidecar-kafka.yaml
    target:
      kind: Deployment
      annotationSelector: "tests/injectKafkaSideCar=true"
      name: ".*"


#
#  - path: sidecar-mysql.yaml
#    target:
#      kind: Deployment
#      annotationSelector: "tests/injectMySqlSideCar=true"
#      name: ".*"
#
  - path: sidecar-postgresql.yaml
    target:
      kind: Deployment
      annotationSelector: "tests/injectPostgresqlSideCar=true"
      name: ".*"

