apiVersion: apps/v1
kind: Deployment
metadata:
  name: doesNotMatter
spec:
  template:
    spec:
      containers:
        - name: postgresql
          image: "quay.io/zgrinber/postgres:latest"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
#          command:
#            - sleep
#            - infinity
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
#              subPath:
              name: db-init

            - mountPath: /tmp
              name: annotations
      volumes:
        - name: db-init
          configMap:
            name: database-init
            defaultMode: 0777
        - name: annotations
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
            defaultMode: 0777