apiVersion: apps/v1
kind: Deployment
metadata:
  name: doesNotMatter
spec:
  template:
    spec:
      containers:
        - name: kafka
          image: "bashj79/kafka-kraft"
          ports:
            - containerPort: 9092
