apiVersion: apps/v1
kind: Deployment
metadata:
  name: doesNotMatter
spec:
  template:
    spec:
      containers:
        - name: kafka
          image: "quay.io/zgrinber/kafka-kraft:latest"
          ports:
            - containerPort: 9092
