apiVersion: apps/v1
kind: Deployment
metadata:
  name: doesNotMatter
spec:
  template:
    spec:
      containers:
        - name: postgresql
          image: "postgres:latest"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: APP_DATABASE_NAME
              valueFrom:
                fieldRef: metadata.annotations.postgresqlSideCarDB

          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              subPath: init-db.sh
              name: db-init
      volumes:
        - name: db-init
          configMap:
            name: database-init
            defaultMode: 0777
