resources:
  - ./../base
  - rbac.yaml
patches:
  - patch: |-
       apiVersion: apps/v1
       kind: Deployment
       metadata:
         name: doesNotMatter
       spec:
         template:
           spec:
             securityContext:
               runAsUser: 0
             serviceAccountName: app-tester
    target:
      kind: Deployment
      name: ".*"  
