kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anyuid-scc-role
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["anyuid"]
    verbs: ["use"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-tester
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anyuid-scc-role-binding
subjects:
  - kind: ServiceAccount
    name: app-tester
roleRef:
  kind: Role
  name: anyuid-scc-role
  apiGroup: rbac.authorization.k8s.io
